# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='NameOfPost', max_length=50),
        ),
    ]
